import React, { useState } from 'react';

export default function AnalysisPanel({ analysis, topic }) {
  const [expanded, setExpanded] = useState(true);

  // Convert markdown-like text to structured HTML
  const formatAnalysis = (text) => {
    if (!text) return '';
    return text
      .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
      .replace(/^#{1,3}\s+(.+)$/gm, '<h3>$1</h3>')
      .replace(/^\d+\.\s+\*\*(.*?)\*\*:?\s*/gm, '<h3>$1</h3>')
      .replace(/^\d+\.\s+/gm, '')
      .replace(/\n\n/g, '</p><p>')
      .replace(/\n/g, '<br/>');
  };

  return (
    <div className="border-2 border-neutral-accent bg-white">
      {/* Header */}
      <button
        onClick={() => setExpanded(!expanded)}
        className="w-full flex items-center justify-between px-5 py-4 hover:bg-gray-50 transition-colors"
      >
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 bg-neutral-accent flex items-center justify-center flex-shrink-0">
            <span className="text-white text-sm">⚖</span>
          </div>
          <div className="text-left">
            <div className="section-label text-neutral-accent">AI Neutral Analysis</div>
            <div className="font-display font-bold text-ink text-sm mt-0.5">
              Balanced Fact-Check: {topic}
            </div>
          </div>
        </div>
        <span className="text-gray-400 text-lg transition-transform duration-200" style={{
          transform: expanded ? 'rotate(180deg)' : 'rotate(0deg)'
        }}>
          ▾
        </span>
      </button>

      {expanded && (
        <div className="px-5 pb-5 border-t border-gray-100 animate-fade-in">
          <div
            className="analysis-prose mt-4 text-sm text-gray-700 leading-relaxed"
            dangerouslySetInnerHTML={{
              __html: `<p>${formatAnalysis(analysis)}</p>`
            }}
          />
          <div className="mt-4 pt-3 border-t border-gray-100 flex items-center gap-2">
            <div className="w-2 h-2 rounded-full bg-neutral-accent animate-pulse-slow" />
            <span className="text-xs font-mono text-gray-400">
              Generated by Grok AI · Based only on retrieved articles
            </span>
          </div>
        </div>
      )}
    </div>
  );
}
